In [2]:
import numpy as np
import torch

In [3]:
labelT = torch.rand((1,3,3))
weightT = torch.ones((1,3,3))
maskT = torch.zeros((1,3,3))
print(labelT)
print(weightT)

weightT[0,0,0] = 10
weightT[0,2,1] = 10
weightT[0,0,2] = 10

maskT[0,0,0] = 1
maskT[0,1,1] = 1
maskT[0,2,2] = 1

print(weightT)
print(maskT)

tensor([[[0.9018, 0.4787, 0.3900],
         [0.6485, 0.6399, 0.5297],
         [0.6745, 0.8608, 0.8889]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[10.,  1., 10.],
         [ 1.,  1.,  1.],
         [ 1., 10.,  1.]]])
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])


In [4]:
labelV = labelT.view(-1)
weightV = weightT.view(-1)
maskV = maskT.view(-1)
print(labelV)
print(weightV)
print(maskV)

tensor([0.9018, 0.4787, 0.3900, 0.6485, 0.6399, 0.5297, 0.6745, 0.8608, 0.8889])
tensor([10.,  1., 10.,  1.,  1.,  1.,  1., 10.,  1.])
tensor([1., 0., 0., 0., 1., 0., 0., 0., 1.])


In [5]:
mul = labelV * weightV * maskV
print(mul)
print(mul.sum())

tensor([9.0178, 0.0000, 0.0000, 0.0000, 0.6399, 0.0000, 0.0000, 0.0000, 0.8889])
tensor(10.5466)


In [6]:
a = torch.ones((1,3,3))