In [24]:
import numpy as np
import torch

In [25]:
labelT = torch.rand((1,3,3))
weightT = torch.ones((1,3,3))
maskT = torch.zeros((1,3,3))
print(labelT)
print(weightT)

weightT[0,0,0] = 10
weightT[0,2,1] = 10
weightT[0,0,2] = 10

maskT[0,0,0] = 1
maskT[0,1,1] = 1
maskT[0,2,2] = 1

print(weightT)
print(maskT)

tensor([[[0.2984, 0.6492, 0.6233],
         [0.1130, 0.1377, 0.4759],
         [0.8177, 0.0661, 0.5743]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[10.,  1., 10.],
         [ 1.,  1.,  1.],
         [ 1., 10.,  1.]]])
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])


In [26]:
labelV = labelT.view(-1)
weightV = weightT.view(-1)
maskV = maskT.view(-1)
print(labelV)
print(weightV)
print(maskV)

tensor([0.2984, 0.6492, 0.6233, 0.1130, 0.1377, 0.4759, 0.8177, 0.0661, 0.5743])
tensor([10.,  1., 10.,  1.,  1.,  1.,  1., 10.,  1.])
tensor([1., 0., 0., 0., 1., 0., 0., 0., 1.])


In [27]:
mul = labelV * weightV * maskV
print(mul)
print(mul.sum())

tensor([2.9838, 0.0000, 0.0000, 0.0000, 0.1377, 0.0000, 0.0000, 0.0000, 0.5743])
tensor(3.6957)


In [28]:
targets = torch.rand((2,3,3))
input = torch.rand((1,3,3))
label = targets[0].unsqueeze(0)
print(label.shape)

label[label>=0.5] = 1
label[label<0.5] = 0

print(label)
print(input)

torch.Size([1, 3, 3])
tensor([[[0., 1., 1.],
         [1., 1., 1.],
         [0., 1., 1.]]])
tensor([[[0.2640, 0.4674, 0.2646],
         [0.5692, 0.1292, 0.3594],
         [0.6486, 0.1094, 0.9916]]])


In [29]:
mul = label * input
print(mul)

rd = torch.round(mul)
print(rd)

print(label)

acc = torch.eq(rd, label)
print(acc)

tensor([[[0.0000, 0.4674, 0.2646],
         [0.5692, 0.1292, 0.3594],
         [0.0000, 0.1094, 0.9916]]])
tensor([[[0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 1.]]])
tensor([[[0., 1., 1.],
         [1., 1., 1.],
         [0., 1., 1.]]])
tensor([[[ True, False, False],
         [ True, False, False],
         [ True, False,  True]]])
